export const englishLabel = {
  languageStatus: "en",
  month: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ],
  menu: {
    dashboard: {
      dashboardStatus: "DB",
      dashboardLabel: "Dashboard",
      dashboardTitle: "DASHBOARD",
      dashboardSubtitle: "Welcome to your dashboard",
      buttonLabel: "DOWNLOAD REPORTS",
      dashboardSummary: {
        emailTitle: "Emails sent",
        newUserTitle: "New Users",
        revenueTitle: "Revenue",
        expenseTitle: "Expense",
      },
      financialOverview: {
        revenueTitle: "Revenue Generated",
        transactionTitle: "Recent Transaction",
      },
      saleAnalytics: {
        campaign: {
          campaignTitle: "Campaign",
          campaignSubtitle: "Including miscellaneous spending",
        },
        salesTitle: "Sales Quantity",
        geographyTitle: "Geography based traffic",
      },
    },
    data: {
      dataLabel: "Data",
      manageTeam: {
        manageTeamStatus: "MT",
        manageTeamLabel: "Manage team",
        manageTeamTitle: "TEAM",
        manageTeamSubtitle: "Managing the team Members",
        table: {
          //goes with the header name
          id: "ID",
          name: "Name",
          email: "Email",
          age: "Age",
          phone: "Phone",
          accessLevel: "AccessLevel",
        },
      },
      contacts: {
        contactStatus: "CT",
        contactsLabel: "Contacts information",
        contactTitle: "CONTACT",
        contactSubtitle: "The list of contacts for future reference",
        table: {
          id: "ID",
          registrarId: "Registrar ID",
          email: "Email",
          age: "Age",
          phone: "Phone",
          address: "Address",
          city: "city",
          zipCode: "zip code",
        },
      },
      invoices: {
        invoiceStatus: "IV",
        invoicesLabel: "Invoice Balances",
        invoicesTitle: "INVOICES",
        invoicesSubtitle: "The list of invoices",
        table: {
          id: "ID",
          name: "Name",
          email: "Email",
          cost: "Cost",
          phone: "Phone",
          data: "Data",
        },
      },
    },

    pages: {
      pagesLabel: "Pages",
      profileForm: {
        profileFormStatus: "PF",
        profileFormLabel: "Profile Form",
        profileFormTitle: "CREATE USER",
        profileFormSubtitle: "Create a new user",
        form: {
          firstName: "First Name",
          lastName: "Last Name",
          email: "email",
          contactNumber: "Contact Number",
          address1: "Address 1",
          address2: "Address 2",
          buttonLabel: "CREATE NEW USER",
        },
      },
      calendar: {
        calendarStatus: "CD",
        calendarLabel: "Calendar",
        calendarTitle: "CALENDAR",
        calendarSubtitle: "View you calendar date and make schedules",
        event: "Events",
      },
      faq: {
        faqStatus: "FAQ",
        faqLabel: "FAQ",
        faqTitle: "FAQ",
        faqSubtitle: "Frequently asked questions page",
      },
    },
    charts: {
      chartsLabel: "Charts",
      BarChart: {
        BarChartStatus: "BC",
        BarChartLabel: "Bar Chart",
        BarChartTitle: "BAR CHART",
        BarChartSubtitle: "Sales report",
      },
      PieChart: {
        PieChartStatus: "PC",
        PieChartLabel: "Pie Chart",
        PieChartTitle: "PIE CHART",
        PieChartSubtitle: "Office report",
      },
      LineChart: {
        LineChartStatus: "LC",
        LineChartLabel: "Line Chart",
        LineChartTitle: "LINE CHART",
        LineChartSubtitle: "Revenue report",
      },
      GeographyChart: {
        GeographyChartStatus: "GS",
        GeographyChartLabel: "Geography Chart",
        GeographyChartTitle: "GEOGRAPHY CHART",
        GeographyChartSubtitle: "Very interesting ge chart",
      },
    },
  },
};

export const khmerLabel = {
  languageStatus: "kh",
  month: [
    "មករា",
    "កុម្ភៈ",
    "មីនា",
    "មេសា",
    "ឧសភា",
    "មិថុនា",
    "កក្កដា",
    "សីហា",
    "កញ្ញា",
    "តុលា",
    "វិច្ឆិកា",
    "ធ្នូ",
  ],
  menu: {
    dashboard: {
      dashboardStatus: "DB",
      dashboardLabel: "ផ្ទាំងគ្រប់គ្រង",
      dashboardTitle: "ផ្ទាំងគ្រប់គ្រង",
      dashboardSubtitle: "សូមស្វាគមន៍មកកាន់ផ្ទាំងគ្រប់គ្រងរបស់អ្នក",
      buttonLabel: "ទាញយករបាយការណ៍",
      dashboardSummary: {
        emailTitle: "អ៊ីមែលដែលបានផ្ញើ",
        newUserTitle: "អ្នកប្រើថ្មី",
        revenueTitle: "ប្រាក់ចំណូល",
        expenseTitle: "ប្រាក់​ចំណាយ",
      },
      financialOverview: {
        revenueTitle: "ប្រាក់ចំណូលដែលបានបង្កើត",
        transactionTitle: "ប្រតិបត្តិការថ្មីៗ",
      },
      saleAnalytics: {
        campaign: {
          campaignTitle: "យុទ្ធនាការ",
          campaignSubtitle: "រួមបញ្ចូលការចំណាយផ្សេងៗ",
        },
        salesTitle: "បរិមាណលក់",
        geographyTitle: "ចរាចរណ៍តាមតំបន់ភូមិសាស្ត្រ",
      },
    },
    data: {
      dataLabel: "ទិន្នន័យ",
      manageTeam: {
        manageTeamStatus: "MT",
        manageTeamLabel: "គ្រប់គ្រងក្រុម",
        manageTeamTitle: "ក្រុម",
        manageTeamSubtitle: "ការគ្រប់គ្រងសមាជិកក្រុម",
        table: {
          id: "លេខសម្គាល់",
          name: "ឈ្មោះ",
          email: "អ៊ីមែល",
          age: "អាយុ",
          phone: "ទូរស័ព្ទ",
          accessLevel: "កម្រិតនៃការចូលប្រើ",
        },
      },
      contacts: {
        contactStatus: "CT",
        contactsLabel: "ព័ត៌មានទំនាក់ទំនង",
        contactTitle: "ទំនាក់ទំនង",
        contactSubtitle: "បញ្ជីទំនាក់ទំនងសម្រាប់យោងទៅមុខ",
        table: {
          id: "លេខសម្គាល់",
          registrarId: "លេខសម្គាល់អ្នកចុះឈ្មោះ",
          email: "អ៊ីមែល",
          age: "អាយុ",
          phone: "ទូរស័ព្ទ",
          address: "អាសយដ្ឋាន",
          city: "ទីក្រុង",
          zipCode: "លេខកូដប្រៃសណីយ៍",
        },
      },
      invoices: {
        invoiceStatus: "IV",
        invoicesLabel: "តុល្យភាពវិក្កយបត្រ",
        invoicesTitle: "វិក្កយបត្រ",
        invoicesSubtitle: "បញ្ជីវិក្កយបត្រ",
        table: {
          id: "លេខសម្គាល់",
          name: "ឈ្មោះ",
          email: "អ៊ីមែល",
          cost: "ថ្លៃដើម",
          phone: "ទូរស័ព្ទ",
          data: "ទិន្នន័យ",
        },
      },
    },

    pages: {
      pagesLabel: "ទំព័រ",
      profileForm: {
        profileFormStatus: "PF",
        profileFormLabel: "បែបបទប្រវត្តិរូប",
        profileFormTitle: "បង្កើតអ្នកប្រើ",
        profileFormSubtitle: "បង្កើតអ្នកប្រើថ្មី",
        form: {
          firstName: "នាមខ្លួន",
          lastName: "នាមត្រកូល",
          email: "អ៊ីមែល",
          contactNumber: "លេខទំនាក់ទំនង",
          address1: "អាសយដ្ឋាន ១",
          address2: "អាសយដ្ឋាន ២",
          buttonLabel: "បង្កើតអ្នកប្រើថ្មី",
        },
      },
      calendar: {
        calendarStatus: "CD",
        calendarLabel: "ប្រតិទិន",
        calendarTitle: "ប្រតិទិន",
        calendarSubtitle: "មើលប្រតិទិនរបស់អ្នក និងរៀបចំកាលវិភាគ",
        event: "ព្រឹត្តិការណ៍",
      },
      faq: {
        faqStatus: "FAQ",
        faqLabel: "សំណួរដែលគេសួរញឹកញាប់",
        faqTitle: "សំណួរដែលគេសួរញឹកញាប់",
        faqSubtitle: "ទំព័រសំណួរដែលគេសួរញឹកញាប់",
      },
    },
    charts: {
      chartsLabel: "តារាង",
      BarChart: {
        BarChartStatus: "BC",
        BarChartLabel: "តារាងបារី",
        BarChartTitle: "តារាងបារី",
        BarChartSubtitle: "របាយការណ៍លក់",
      },
      PieChart: {
        PieChartStatus: "PC",
        PieChartLabel: "តារាងគ្រាប់បែប",
        PieChartTitle: "តារាងគ្រាប់បែប",
        PieChartSubtitle: "របាយការណ៍ការិយាល័យ",
      },
      LineChart: {
        LineChartStatus: "LC",
        LineChartLabel: "តារាងបន្ទាត់",
        LineChartTitle: "តារាងបន្ទាត់",
        LineChartSubtitle: "របាយការណ៍ប្រាក់ចំណូល",
      },
      GeographyChart: {
        GeographyChartStatus: "GS",
        GeographyChartLabel: "តារាងភូមិសាស្ត្រ",
        GeographyChartTitle: "តារាងភូមិសាស្ត្រ",
        GeographyChartSubtitle: "តារាងភូមិសាស្ត្រដ៏គួរឱ្យចាប់អារម្មណ៍",
      },
    },
  },
};
